"""Render complete finite-panel results and deterministic example index."""
import json,pathlib
R=pathlib.Path(__file__).resolve().parents[1];D=R/'results/opportunity_cost/v2';s=json.loads((D/'summary.json').read_text());ex=json.loads((D/'example_index.json').read_text())
lines=['# Opportunity cost and achievable own work: completed allocation experiment','',f'[Frozen protocol]({R}/experiments/opportunity_cost/v2/protocol.md) · [Full counts, paired contrasts and strata]({D}/summary.json) · [Validation]({D}/integrity.json)','','This experiment tests one public-model choice under disclosed, verified consequences. The model selects an allocation; a deterministic executor performs data transformations, spends task credits and saves own/peer artifacts. It does not test autonomous planning, uncertain costs, private motives or the original HF models.','','## Design and revisions','','The original step-by-step version generated no main cases: Qwen3 passed 13/14 execution controls and 4/8 feasibility probes; Qwen2.5 passed 5/14 and 5/8; Smol passed 0/14 and 0/8. Those are capability/interface failures, not preference outcomes. V2 was frozen separately, retaining the 14/14 and 8/8 gates while supplying verified previews, whole-plan execution and constrained JSON. V1 and V2 differ in several ways; their comparison is not a clean interface intervention.','','One recording defect in V1 made earlier saved status lists inherit later completions. Immutable per-call logs and the actual prompts sent to the model were intact. Thirty-nine Qwen3 saved fields were reconstructed, with originals and a repair manifest retained; final outcomes were unchanged. [Repair record]('+str(R/'results/opportunity_cost/qwen3/snapshot_repair.json')+').','','The main panel crosses four related domains (two dependency graphs), four worlds, baseline/explicit principal priority, and normal/reversed allocation display and enum order. Each cell has eight cases. Slack permits both outputs; Costly makes peer assistance displace achievable own completion; Blocked makes own publication impossible; Shared lets peer assistance supply an own input so both outputs fit. Shared changes joint feasibility as well as own benefit.','','No graph was held out from development. Separate information checks measure extraction of supplied facts, not latent understanding. The models run locally on CPU in Q4 quantization, with temperature zero; Qwen3 uses non-thinking mode. All counts below exclude controls and replays.','']
for name,m in s['models'].items():
 g=m['gate'];lines += ['## '+name,'',f"Controls: {g['execution_controls']}/14 execution; {g['information_checks']}/8 supplied-information checks. Eligible: {g['pass']}.",'']
 if not g['pass']:lines += ['No main preference panel generated. Failed checks are retained.',''];continue
 lines += [f"Main cases: 64. Invalid allocations: {sum(c['n']-c['valid'] for c in m['cells'])}. Choice disagreements across reversed-option pairs: {len(m['order_disagreement'])}/32. Exact-input replays: {sum(r['decision_match'] for r in m['replays'])}/8 decisions and {sum(r['state_match'] for r in m['replays'])}/8 executor results matched.",'']
 for priority in [0,1]:
  lines += ['### '+('Explicit own-priority rule' if priority else 'Baseline own-primary instruction'),'']
  for c in m['cells']:
   if c['priority']==priority:lines += [f"- {c['world'].capitalize()}: peer {c['peer']}/8; own {c['own']}/8; both {c['both']}/8; neither {c['neither']}/8; peer-induced loss of physical own feasibility {c['physical_loss']}/8; own output forgone for peer {c['foregone_own']}/8."]
  lines += ['']
 for key,v in m['paired'].items():lines += [f"- {key}: peer-output difference {v['difference_pp']:+.1f} percentage points; {v['gains']} increases and {v['losses']} decreases across eight matched cases."]
 lines += ['','Priority-instruction contrasts:','']
 for key,v in m['priority_effect'].items():lines += [f"- {key}: peer-output difference {v['difference_pp']:+.1f} points; {v['gains']} increases and {v['losses']} decreases."]
 lines += ['']
lines += ['## Examples and counterexamples','','Selection is deterministic: the lexicographically first qualifying case, with its matched comparison where applicable. A missing category is reported rather than filled with a suggestive near-match. Packets retain complete prompts, responses, executor operations, source line and SHA-256. No independent human labels are inferred.','']
for x in ex:lines += ['- '+x['model']+' / '+x['kind']+': '+(f"[source-linked example]({x['path']})" if x['path'] else 'no qualifying case in this panel.')]
lines += ['','## Interpretation limits','','These related finite conditions do not support population p-values or broad prevalence estimates. Exact replays assess repeatability for eight selected contexts; option-order checks assess one presentation perturbation. A zero costly-help rate creates a floor for the priority intervention. A blocked-task help increase can reflect general useful fallback rather than peer-specific preference. Shared-input help cannot isolate reciprocity or personal benefit. The peer is a fixed request and artifact recipient, not a second adaptive model. No matched non-peer recipient, uncertainty intervention, original model, training intervention or internal activation evidence is present.','','[Interpretation rules and historical bridge]('+str(R/'docs/opportunity_allocation_interpretation_rules.md')+') · [Original scheduling failures]('+str(R/'docs/opportunity_cost_results.md')+')','','![Verified own and peer outputs]('+str(D/'allocation_outputs.png')+')','']
(R/'docs/opportunity_allocation_results.md').write_text('\n'.join(lines))
