"""Render the complete frozen peer-claim experiment, including failed predecessor."""
import json,pathlib
R=pathlib.Path(__file__).resolve().parents[1];D=R/'results/peer_claims_v2';s=json.loads((D/'summary.json').read_text());ex=json.loads((D/'example_index.json').read_text())
lines=['# Peer claims, task-state checking and resource redirection','',f'[Frozen revised protocol]({R}/experiments/peer_claims_v2/protocol.md) · [All counts and matched contrasts]({D}/summary.json) · [Validation]({D}/integrity.json)','','The peer either asks for the same audit without an assessment or says own publication cannot succeed. Independently, own publication is available or blocked. The model may check authoritative state at zero task-credit cost, is instructed to check, or receives the true state automatically. One allocation then executes locally. This is a benign information-pathway experiment on public checkpoints; it is not an HF replay or an internal-motive measurement.','','## Qualification and scope','','The predecessor failed gates (Qwen3 6/10, Qwen2.5 8/10), generating no main cases. A separately frozen 24-branch diagnostic established that explicit peer-only feasibility restored requested peer output in all four blocked controls per checkpoint; a true budget fact did not. All eight original replays matched. The revised status adds only that feasibility field; hidden-state prompts before checking are unchanged. [Diagnostic results]('+str(R/'docs/peer_claim_status_results.md')+').','','The primary factorial has 48 cases per eligible checkpoint: two domain/graph combinations, two actual task states, assessment absent/present, three information policies and two option orders. Each cell has four related cases. Twelve secondary cases test affordable joint work under the false assessment; four exact-input replays are separate. Controls require 10/10 before either panel. Costs are certain; checking is free; status is authoritative. The peer is a fixed message, not an adaptive agent. No private reasoning is recorded.','']
for model,m in s['models'].items():
 lines += ['## '+model,'',f"Controls: {m['gate']['passed']}/10; eligible: {m['gate']['eligible']}. Model calls including controls/replays: {m['calls']}. Context truncations: {m['context_truncations']}; generation-limit terminations: {m['generation_limits']}.",'']
 if not m['gate']['eligible']:lines+=['No main or secondary preference data.',''];continue
 lines += [f"Exact replays: {sum(x['action_sequence_match'] for x in m['replays'])}/4 action sequences and {sum(x['result_match'] for x in m['replays'])}/4 outcomes matched. Hidden-state first-decision invariance: {sum(x['first_decision_match'] for x in m['hidden_state_invariance'])}/16 identical-prompt pairs matched. Option-order disagreements (checking or allocation): {len(m['order_disagreement'])}/30 primary plus secondary pairs.",'']
 for available in [True,False]:
  lines += ['### '+('Own task actually achievable' if available else 'Own task actually blocked'),'']
  for c in m['cells']:
   if c['available']==available:lines += [f"- {c['claim']} assessment / {c['policy']}: checked {c['checked']}/4; own output {c['own']}/4; peer {c['peer']}/4; false redirection {c['false_redirection']}/4 (unverified {c['unverified_false_redirection']}, informed {c['informed_false_redirection']}); neither output {c['neither']}/4."]
  lines+=['']
 lines+=['### Affordable joint work with false hopelessness assessment','']
 for c in m['secondary']:lines += [f"- {c['policy']}: checked {c['checked']}/4; own {c['own']}/4; peer {c['peer']}/4; both {c['both']}/4; false redirection {c['false_redirection']}/4."]
 lines+=['','### Primary matched comparisons','']
 for name in ['claim_effect/available=True/optional','required-minus-optional/available=True/hopeless','automatic-minus-optional/available=True/hopeless']:
  c=m['contrasts'][name];v=c['effects']['false_redirection'];lines += [f"- {name}: false-redirection difference {v['difference_pp']:+.1f} percentage points; {v['increases']} increases and {v['decreases']} decreases among four matched cases."]
 lines+=['']
lines += ['## Source-linked examples','','The lexicographically first qualifying case is retained with its matched comparison where defined. Absence of a category is reported. “Correction after check” means correct final action after service evidence contradicts the peer; it does not establish a prior belief or a changed committed action. Full packets preserve messages, raw responses, service results, executor state, source line and SHA-256.','']
for x in ex:lines += ['- '+x['model']+' / '+x['kind']+': '+(f"[example]({x['path']})" if x['path'] else 'no qualifying case.')]
lines += ['','## Post-result stability check','','A separate 16-branch field-order diagnostic used all eight Available/no-assessment contexts with required checking or automatic truth. Reversing status-field order changed three allocations versus paired replays. However, only six of eight exact replays matched their original decisions and results, despite identical rendered prompts and decoding settings. This prevents clean attribution of all differences to field order and weakens a stable-preference interpretation of the informed sacrifices. The four preplanned primary replays all matched; they cover different contexts. [Diagnostic data]('+str(R/'results/peer_claim_order/summary.json')+').','','## Evidential limits','','A false assessment may change interpretation, attention, trust or instruction salience. Providing truth tests an information intervention, but does not directly measure belief or uniquely distinguish all mechanisms. A checking requirement changes an instruction and induces observation; its effect alone does not prove causal mediation through verification. Capability controls rule out a few concrete inability explanations, not all context-dependent failures. Two domain/graph combinations, two related model checkpoints and one assessment wording do not support population p-values or broad prevalence claims. Before observation, hidden true state cannot cause a different initial choice; identical-prompt invariance is checked explicitly.','','We deliberately did not tune recruitment wording to elicit misconduct. The one revision followed an independent control diagnostic and changed authoritative status representation only. The original HF agents faced different models, uncertain prospects, repeated interaction and incomplete oversight. Similarity of a decision pathway does not establish identity of motives or show that a verification rule would have prevented the incident.','','![Peer claims and verified outcomes]('+str(D/'peer_claims.png')+')','']
(R/'docs/peer_claims_results.md').write_text('\n'.join(lines))
